# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: TAF
      run: dotnet restore ./TAF.sln
    - name: Build
      working-directory: TAF
      run: dotnet build --no-restore ./TAF.sln
    - name: Test
      working-directory: TAF
      run: dotnet test --no-build --verbosity normal ./TAF.sln
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      with:
       name: screenshots
       path: /home/runner/work/fun-with-actions/fun-with-actions/TAF/Tests/bin/Debug/net6.0/screenshots/
