name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: TAF
      run: dotnet restore ./TAF.sln
    - name: Build
      working-directory: TAF
      run: dotnet build --no-restore ./TAF.sln
    - name: API Tests
      working-directory: TAF
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~Tests.Tests.API
    - name: Page Tests
      working-directory: TAF
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName!=Tests.Tests.API
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
       name: screenshots
       path: /home/runner/work/fun-with-actions/fun-with-actions/TAF/Tests/bin/Debug/net6.0/screenshots/
